### Create team
POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "name": "demoTeam"
}

### Get team
GET http://localhost:8080/api/teams/2

### Update team
PUT http://localhost:8080/api/teams/2
Content-Type: application/json

{
  "name": "demoTeamUpdated"
}

### Delete team
DELETE http://localhost:8080/api/teams/2

### Create employee
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "name": "demoName",
  "email": "demoUser",
  "password": "demoHashedPassword",
  "role": "ADMIN",
  "team": "/api/teams/2"
}

### Get employee
GET http://localhost:8080/api/teams/2/employees

### Create employee task
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "tasksToday": "demoTasksToday",
  "tasksYesterday": "demoTasksYesterday",
  "impediments": "demoImpediments",
  "employee": "/api/employees/3"
}

### Get employee task
GET http://localhost:8080/api/employees/3/tasks

### Create issue
POST http://localhost:8080/api/issues
Content-Type: application/json

{
  "issuesToday": "demoIssuesToday"
}

### Get issue
GET http://localhost:8080/api/issues/3